### ISSUE TITLE
NoNodes when calling generate-elastic-search.pl

### ISSUE THREAD

**Issue by apaytuvi** [cmdcolin/jbrowse_elasticsearch#3]
I got the following error:

```
perl bin/generate-elastic-search.pl --out ../data/data/ --tracks esearch_transcript
[NoNodes] ** No nodes are available: [http://localhost:9200], called from sub Search::Elasticsearch::Client::5_0::Role::Bulk::index at /media/sequentia/synology_server/melonomics/client/JBrowse-1.12.3/jbrowse_elasticsearch/bin/../src/perl5/Bio/JBrowse/Cmd/ElasticSearch.pm line 104.
```

How can I solve it?

**Comment by cmdcolin** [comment]
I think that just means that the elasticsearch server isn't running yet. Elasticsearch normally runs a server on port 9200. If you are on ubuntu and you installed elasticsearch via their instructions here https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html then you can run `sudo service elasticsearch start` to start it up (that's my preferred way of installing it anyways. there are different ways to install but having it as a system service is the easiest IMO)

**Comment by cmdcolin** [comment]
Was this ever fixed :)?

**Comment by apaytuvi** [comment]
Yes, this was fixed. Thank you!
