### ISSUE TITLE
[Question] About indexing

### ISSUE THREAD

**Issue by hsiaoyi0504** [cmdcolin/jbrowse_elasticsearch#6]
Hi, I am new to jbrowse and this plugin. I just get confused how to use this plugin. In Jbrowse document mentioned, it needs to run `generate_names.pl` to create index. However, I am not sure if I need to do that at this case, or I just need to use `prepare-refseqs.pl`, `flatfile-to-json.pl`, and `generate_elastic_search.pl`. Can someone help me this ?

**Comment by cmdcolin** [comment]
Essentially you can do both generate-names and generate-elastic-search

The plugin here makes a custom menu item for searching and should supplant most of the functionality of generate-names but the generate-names is still useful to run. For example the box that shows your location doubles as a search box that generate-names uses. Also doing ?loc=somegeneid in the url bar will also look in the plain generate-names index too, so if you want that then generate-names is still useful there.  Technically all the stuff that generate-names does could be overridden directly (see Names API in jbrowse docs) but this plugin doesn't implement the Names API yet so doing both generate commands is useful

**Comment by hsiaoyi0504** [comment]
Thanks
