### ISSUE TITLE
Reverse proxy

### ISSUE THREAD

**Issue by romens96** [cmdcolin/jbrowse_elasticsearch#8]
Im new in deaing with reverse proxy issue

I managed to run elasticsearch on a localhost but i am not sure how to configure the reverse proxy so that public can use the elasticsearch feature on the jbrowse i uploaded to cloud server
can anyone help in providing a link with tutorial on how to set this reverse proxy up?

**Comment by cmdcolin** [comment]
Hi @romens96 

Reverse proxy is not essential for any setup, the purpose of reverse proxy is to allow a service running on

http://yourhost:1234

to map to

http://yourhost/some_suburl/

Therefore, if you can open up port 1234 to the outside world, then you don't even need to reverse proxy. Many cloud servers allow you to open up arbitrary ports. Some institutional networks only allow some specific port so in that situation it is important to reverse proxy

**Comment by romens96** [comment]
Fixed the problem of reverse proxy. Thanks for the assistance
